#!/bin/sh

# see: https://github.com/Homebrew/homebrew-bundle

brew "ack"
brew "ag"
brew "autoenv"
brew "automake"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bfg"
brew "bzt"
brew "cmake"
brew "coreutils"
brew "csshX"
brew "ctags-exuberant"
brew "ctop"
brew "curl"
brew "fd"
brew "findutils" # find, locate, updatedb, xargs
brew "fzf"
brew "gh"
brew "git"
brew "gpg"
brew "hub"
brew "k9s"
brew "libgccjit"
brew "libidn"
brew "lzlib"
brew "mysql"
brew "nvm"
brew "openssl"
brew "pstree"
brew "ripgrep"
brew "rlwrap"
brew "readline"
brew "svn" # needed for the occasional brew package
brew "terminal-notifier"
brew "tldr"
brew "tmux"
brew "watch"
brew "webp"
brew "wget"
brew "webpack"
brew "yamllint"
brew "yq"

tap "d12frosted/emacs-plus"
brew "emacs-plus@29", args: ["with-imagemagick"], restart_service: :changed

# langs and development

brew "clojure"
brew "golang"
brew "jenv"
brew "leiningen"
brew "node"
brew "python@3.9"
brew "flake8"
brew "pyenv"
brew "pyenv-virtualenv"
brew "poetry"
brew "rbenv"
brew "rbenv-bundler"
brew "ruby@2.7"
brew "ruby-build"
brew "postgresql@14"
brew "virtualenv"
brew "yarn"

# apps

cask "docker"
cask "github"
cask "handbrake"
cask "iterm2"
cask "postman"
cask "rectangle"
cask "sourcetree"
cask "visual-studio-code"
cask "vlc"

tap "homebrew/cask-fonts"

cask "font-camingocode"
cask "font-hack"
cask "font-inconsolata"
cask "font-juliamono"
cask "font-profont-nerd-font"
cask "font-roboto-mono"
cask "font-roboto-mono-nerd-font"
cask "font-source-code-pro"
